/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.anderfred.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Vacancy service. Represents a row in the &quot;vacancy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.anderfred.model.impl.VacancyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.anderfred.model.impl.VacancyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Vacancy
 * @generated
 */
@ProviderType
public interface VacancyModel extends BaseModel<Vacancy> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vacancy model instance should use the {@link Vacancy} interface instead.
	 */

	/**
	 * Returns the primary key of this vacancy.
	 *
	 * @return the primary key of this vacancy
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this vacancy.
	 *
	 * @param primaryKey the primary key of this vacancy
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this vacancy.
	 *
	 * @return the ID of this vacancy
	 */
	public int getId();

	/**
	 * Sets the ID of this vacancy.
	 *
	 * @param id the ID of this vacancy
	 */
	public void setId(int id);

	/**
	 * Returns the published date of this vacancy.
	 *
	 * @return the published date of this vacancy
	 */
	@AutoEscape
	public String getPublishedDate();

	/**
	 * Sets the published date of this vacancy.
	 *
	 * @param publishedDate the published date of this vacancy
	 */
	public void setPublishedDate(String publishedDate);

	/**
	 * Returns the employer of this vacancy.
	 *
	 * @return the employer of this vacancy
	 */
	@AutoEscape
	public String getEmployer();

	/**
	 * Sets the employer of this vacancy.
	 *
	 * @param employer the employer of this vacancy
	 */
	public void setEmployer(String employer);

	/**
	 * Returns the text of this vacancy.
	 *
	 * @return the text of this vacancy
	 */
	@AutoEscape
	public String getText();

	/**
	 * Sets the text of this vacancy.
	 *
	 * @param text the text of this vacancy
	 */
	public void setText(String text);

	/**
	 * Returns the salary of this vacancy.
	 *
	 * @return the salary of this vacancy
	 */
	@AutoEscape
	public String getSalary();

	/**
	 * Sets the salary of this vacancy.
	 *
	 * @param salary the salary of this vacancy
	 */
	public void setSalary(String salary);

}